### PR TITLE
Support Coherence v0.5.2. 

### PR DESCRIPTION
**Pull request by jung-hunsoo**
This PR supports the latest Coherence v0.5.2.

Additionally some warnings are removed.

### CODE REVIEW

**Comment by jung-hunsoo** [comment]
While making PR, I was amazed that the test specs are well described.

**Comment by danschultzer** [comment]
Quick note, the error in CI is because of yet another breaking change 🙄 https://github.com/smpallen99/coherence/commit/ba99eb2f3e458c7e548605c70162e77346d1f5d9#diff-55be929e68b3eb1f6a98fa9a587546c5

Where it goes wrong: https://github.com/danschultzer/coherence_assent/blob/master/test/test_helper.exs#L31

**Comment by danschultzer** [comment]
I'm in the process of releasing `v0.3.2` with coherence locked at `v0.5.0` first, and then I'll rebase this PR and release one that support `v0.5.1+`.

**Comment by jung-hunsoo** [comment]
@danschultzer It's adequate first freeze `v0.3.2` for `Coherence v0.5.0`.

`remove --controllers` was changed in `v0.5.2` tag, which means it's still valid on `v0.5.1`... OMG complicated dependency. It need to be consider whether drop support of `Coherence v0.5.1`.

And also strange that the test was passed locally; Elixir 1.7.0 with OTP 21.

**Comment by danschultzer** [comment]
The Elixir 1.7 test issue in CI is just credo. I'm fixing it in #24.

I think the best approach is to just require `v0.5.2` and up, and don't have any support for `v0.5.1` at all. These are some messy releases 😭

**Comment by jung-hunsoo** [comment]
@danschultzer A lot is going to be changed on `v0.4.0`.

It's reasonable to support `v0.5.2` and up on `v0.4.0` since `v0.4.0` is mainly to get align with the recent Coherence.

**Pull request merged**
