### PR TITLE
OAuth2 Strategy for Basecamp (37signals)

### PR DESCRIPTION
**Pull request by SiriusDely**

### CODE REVIEW

**Comment by danschultzer** [comment]
Thanks @siriusdely! It looks great, and I think there're a few improvements I can do to the OAuth2 strategy to simplify the integration.

Could you please add an integration test similar to this: https://github.com/danschultzer/coherence_assent/blob/master/test/coherence_assent/strategies/google_test.exs

That way we'll make sure to catch any backwards-compatible changes to the auth strategy that could affect the basecamp strategy too.

**Comment by SiriusDely** [comment]
OK, will do. Thanks @danschultzer for pointing to the integration test.

**Comment by danschultzer** [comment]
I've refactored the library to make it simpler to do this integration. I don't have permission to update your PR, but you can take a look at: https://github.com/danschultzer/coherence_assent/commit/debbae5e1ab2ebf12979f32e08aa54413a54a04b

Added an integration test too. Let me know if this works, feel free to cherry-pick the commit.

**Comment by SiriusDely** [comment]
I have cherry-picked your commit, and tested with my basecamp integration and works. Thanks!

**Comment by danschultzer** [comment]
Now released in v0.2.1. Thanks @siriusdely!

**Comment by SiriusDely** [comment]
Nice! Thanks @danschultzer!

**Pull request merged**
